### ISSUE TITLE
Feature request: Network Manager - Support hot spot connection

### ISSUE THREAD

**Issue by manfredu** [project-trident/trident-utilities#1]
It would be great if network manager would support a wifi connection thru a hot spot as described on https://wiki.voidlinux.org/Network_Configuration#Connecting_to_hotel_.2F_restaurant_.2F_airport_hotspots_via_the_command_line.

In my case I would like to connect to the wifi network while traveling by train. The wlan provided by the train operator requires login on a web page. The web page is not shown when using network manager...

**Comment by beanpole135** [comment]
Resolved in the 2020.06.07 release.
Now it properly handles open network setup just fine (key-mgmt=NONE), and if this is the first time you connect to that network, it will even launch the browser on an http url so that any capture portal can open up as needed.
